# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
target 'LifeBox' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
   
   #加载框
   pod 'MBProgressHUD'
   
   #网络请求
   pod 'AFNetworking'
   
   #键盘控制库
   pod 'IQKeyboardManager'
   
   #网络图片请求
   pod 'SDWebImage'
   
   #网络监听
   pod 'Reachability'
   
   #轮播
   pod 'SDCycleScrollView'
   
   #适配
   pod 'Masonry'
   pod 'SnapKit'
   
   #上下拉刷新
   pod 'MJRefresh'
   
   
   #模型转换
   pod 'YYKit'
   pod 'BlocksKit'
   
   pod 'AlipaySDK-iOS'
   pod 'SuperPlayer'
   
   #空数据界面
   pod 'DZNEmptyDataSet'
   
   #日志
   pod 'CocoaLumberjack'
   
   #字体
   pod 'FontAwesome+iOS', :git => 'https://github.com/alexdrone/ios-fontawesome' #fontawesome字体
  
   pod 'UGBox/all', :git => "https://gitee.com/UbunGit/UGOCMagicbox.git" #fontawesome字体
   
   #哆啦A梦测试盒
   pod 'DoraemonKit/Core', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.1', :configurations => ['Debug'] #必选
   pod 'DoraemonKit/WithLogger', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.1', :configurations => ['Debug'] #可选
   pod 'DoraemonKit/WithGPS', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.1', :configurations => ['Debug'] #可选
   pod 'DoraemonKit/WithLoad', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.1', :configurations => ['Debug'] #可选
   pod 'DoraemonKit/WithDatabase', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.1', :configurations => ['Debug'] #可选
   pod 'DoraemonKit/WithMLeaksFinder', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.1', :configurations => ['Debug'] #可选
   pod 'DoraemonKit/WithWeex', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.1', :configurations => ['Debug'] #可选

  # Pods for LifeBox

  target 'LifeBoxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LifeBoxUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
