# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'BusinseeLifeBox' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
   
   #加载框
   pod 'MBProgressHUD', '~> 1.1.0'
   
   #网络请求
   pod 'AFNetworking'
   
   #键盘控制库
   pod 'IQKeyboardManager'
   
   #网络图片请求
   pod 'SDWebImage'
   
   #网络监听
   pod 'Reachability'
   
   #轮播
   pod 'SDCycleScrollView'
   
   #适配
   pod 'Masonry'
   
   #模型转换
#   pod 'YYModel'
   pod 'YYKit'
   pod 'BlocksKit'
   
   pod 'AlipaySDK-iOS'
   
   #空数据界面
   pod 'DZNEmptyDataSet'
   
   #日志
   pod 'CocoaLumberjack'
   
   #哆啦A梦测试盒
   pod 'DoraemonKit/Core', :configurations => ['Debug']
   pod 'DoraemonKit/WithLogger',  :configurations => ['Debug']
   pod 'DoraemonKit/WithGPS',  :configurations => ['Debug']
   pod 'DoraemonKit/WithLoad',  :configurations => ['Debug']
  # pod 'DoraemonKit/WithWeex',  :configurations => ['Debug']
   pod 'DoraemonKit/WithDatabase',  :configurations => ['Debug'] 

  # Pods for BusinseeLifeBox





end
